[package]
name = "game-night"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.74"
chrono = "0.4.26"
chrono-tz = "0.4"
diceware_wordlists = "1.2.1"
dirs = "5.0.1"
email_address = "0.2.4"
hex = { version = "0.4.3", features = ["serde"] }
lettre = { version = "0.10.4", default-features = false, features = ["builder", "file-transport", "smtp-transport", "async-std1", "async-std1-rustls-tls", "serde"] }
rand = "0.8.5"
rocket = { version = "=0.5.0-rc.3", features = ["secrets", "json"] }
rocket_db_pools = { version = "=0.1.0-rc.3", features = ["sqlx_sqlite"] }
rocket_dyn_templates = { version = "=0.1.0-rc.3", features = ["tera"] }
serde = { version = "1.0", features = ["derive"] }
json = { package = "serde_json", version = "1.0.105" }
sqlx = { version = "0.7", features = ["chrono"] }
tera = "1.19.0"
yansi = "1.0.0-rc"
constcat = "0.3.0"
url = "2.4"

[features]
tls = ["rocket/tls"]

[patch.crates-io]
rocket = { git = "https://github.com/bash/Rocket/", branch = "game-night" }
rocket_codegen = { git = "https://github.com/bash/Rocket/", branch = "game-night" }
rocket_http = { git = "https://github.com/bash/Rocket/", branch = "game-night" }
rocket_db_pools = { git = "https://github.com/bash/Rocket/", branch = "game-night" }
rocket_db_pools_codegen = { git = "https://github.com/bash/Rocket/", branch = "game-night" }
rocket_dyn_templates = { git = "https://github.com/bash/Rocket/", branch = "game-night" }
