[package]
name = "game-night"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
diceware_wordlists = "1.2.1"
email_address = "0.2.4"
rand = "0.8.5"
rocket = { version = "=0.5.0-rc.3", features = ["secrets"] }
rocket_db_pools = { version = "=0.1.0-rc.3", features = ["sqlx_sqlite"] }
rocket_dyn_templates = { version = "=0.1.0-rc.3", features = ["tera"] }
sqlx = "0.6.0"
yansi = "0.5.1"
