[package]
name = "game-night"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.74"
diceware_wordlists = "1.2.1"
dirs = "5.0.1"
email_address = "0.2.4"
hex = { version = "0.4.3", features = ["serde"] }
lettre = { version = "0.11.0", default-features = false, features = ["builder", "file-transport", "smtp-transport", "async-std1", "async-std1-rustls-tls", "serde"] }
rand = "0.8.5"
rocket = { version = "=0.5.0-rc.4", features = ["secrets", "json"] }
rocket_db_pools = { version = "=0.1.0-rc.4", features = ["sqlx_sqlite"] }
rocket_dyn_templates = { version = "=0.1.0-rc.4", features = ["tera"] }
serde = { version = "1.0", features = ["derive"] }
json = { package = "serde_json", version = "1.0.105" }
sqlx = { version = "0.7", features = ["time"] }
tera = "1.19.0"
yansi = "1.0.0-rc"
constcat = "0.3.0"
url = "2.4"
uuid = { version = "1.4.1", features = ["v4"] }
itertools = "0.11.0"
opener = "0.6.1"
time = { version = "0.3.28", features = ["formatting", "serde", "local-offset", "macros"] }
time-tz = "2.0.0"
pulldown-cmark = "0.9.3"
dyn-clone = "1.0.14"
ics = "0.5.8"
lazy_static = "1.4.0"

[target.'cfg(target_os = "linux")'.dependencies]
systemd = "0.10.0"

[features]
tls = ["rocket/tls"]
