[package]
name = "game-night"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "game-night"

[dependencies]
anyhow = "1.0.74"
diceware_wordlists = "1.2.1"
email_address = "0.2.4"
lettre = { version = "0.10.4", default-features = false, features = ["builder", "file-transport", "smtp-transport", "async-std1", "async-std1-rustls-tls", "serde"] }
libreauth = "0.16.0"
rand = "0.8.5"
rocket = { version = "=0.5.0-rc.3", features = ["secrets"] }
rocket_db_pools = { version = "=0.1.0-rc.3", features = ["sqlx_sqlite"] }
rocket_dyn_templates = { version = "=0.1.0-rc.3", features = ["tera"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = "0.6.0"
tera = "1.19.0"
yansi = "0.5.1"
