volumes:
  outbox:

services:
  outbox:
    image: codeberg.org/tautropfli/outboxd:0.2.2
    volumes:
    - outbox:/var/lib/outboxd
  web:
    build:
      dockerfile: Containerfile
      target: runtime
      args:
      - CARGO_BUILD_FLAGS=--features development
    depends_on:
     outbox:
       condition: service_started
    ports:
    - "8000:8000"
    volumes:
    - ./data:/var/lib/game-night
    - ./public/build:/run/game-night/public:ro
    - ./:/usr/local/etc/game-night:ro
    - ./templates:/usr/local/share/game-night/templates:ro
    - outbox:/run/outbox:ro
    security_opt:
    - label=disable
