[default]
url_prefix = "http://localhost:8000"
allowed_campaigns = ['super-secrit-beta']

[default.databases.sqlite]
url = "database.sqlite"

[default.email]
sender = "Tau's Game Night <game-night@tau.garden>"
# template_dir = "<path to email templates>"
# outbox_dir = "<path to outbox dir>"
