[default]
secret_keys_path = "/var/lib/game-night/keys"
template_dir = "/usr/local/share/game-night/templates"

[default.databases.sqlite]
url = "/var/lib/game-night/database.sqlite"

[default.email]
template_dir = "/usr/local/share/game-night/emails"
outbox_socket = "/run/outbox/outbox.sock"

[default.web_push]
template_dir = "/usr/local/share/game-night/notifications"
