[default]
url_prefix = "http://localhost:8000"
secret_keys_path = "private"

[default.campaign.example]
message = """
Congratulations! 🎉 You used the <em>example</em> campaign to register."""

[default.databases.sqlite]
url = "database.sqlite"

[default.email]
sender = "Tau's Game Night <game-night@tau.garden>"
# template_dir = "<path to email templates>"
# outbox_dir = "<path to outbox dir>"
