[package]
name = "askama-json-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
json = { version = "1.0.140", package = "serde_json" }
proc-macro2-diagnostics = "0.10"
heck = "0.5.0"
