[default]
address = "0.0.0.0"
secret_keys_path = "/var/lib/game-night/keys"

[default.databases.sqlite]
url = "/var/lib/game-night/database.sqlite"

[default.email]
template_dir = "/usr/local/share/game-night/emails"
outbox_socket = "/run/outbox/outbox.sock"
