[default]
url_prefix = "https://localhost:8000"

[default.campaign.example]
message = """
Congratulations! 🎉 You used the <em>example</em> campaign to register."""

[default.email]
sender = "Tau's Game Night <game-night@tau.garden>"
reply_to = "Tau <tau@example.com>"

[default.tls]
certs = "/var/lib/game-night/certs/localhost+2.pem"
key = "/var/lib/game-night/certs/localhost+2-key.pem"

[default.web_push]
vapid_contact = "mailto:game-night@tau.garden"
