name: CI

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install SASS
      run: npm install -g sass
    - name: Install Dependencies
      run: sudo apt-get install --yes libsystemd-dev
    - name: Publish
      run: make publish
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: publish/
        retention-days: 2
