name: CI

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish
      run: make publish
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: publish/
        retention-days: 2
